# Generated by Django 3.2.4 on 2021-07-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('authorImage', models.ImageField(upload_to='media/blog/authorImages/')),
                ('postImage', models.ImageField(upload_to='media/blog/postImages/')),
                ('authorQuote', models.CharField(max_length=150)),
                ('authorLink', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('seoTitle', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=20000)),
                ('timeStamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postcomments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
