# Generated by Django 3.2.4 on 2021-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('phone', models.IntegerField()),
                ('msg', models.TextField(max_length=5000)),
                ('contactedDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
